/**
 * Scene Export Service
 *
 * Exports 3D scenes as standalone packages that can run independently.
 * Supports all 3D libraries: Babylon.js, Three.js, A-Frame, React Three Fiber.
 */

import { isElectron, getElectronAPI } from './platform'

export type ExportFormat = 'zip' | 'html' | 'json'

export interface ExportOptions {
  format?: ExportFormat
  includeReadme?: boolean
  minify?: boolean
  libraryId: string
  filename?: string
}

export interface ExportResult {
  success: boolean
  filename?: string
  path?: string
  error?: string
  data?: Uint8Array | string
}

/**
 * Export a scene as a standalone package
 */
export async function exportScene(
  code: string,
  options: ExportOptions
): Promise<ExportResult> {
  const { libraryId, format = 'zip', includeReadme = true, filename } = options

  try {
    // Generate the appropriate template
    let exportData: { files: Record<string, string>; mainFile: string }

    switch (libraryId) {
      case 'babylonjs':
        exportData = generateBabylonJSExport(code, includeReadme)
        break
      case 'threejs':
        exportData = generateThreeJSExport(code, includeReadme)
        break
      case 'aframe':
        exportData = generateAFrameExport(code, includeReadme)
        break
      case 'react-three-fiber':
        exportData = generateR3FExport(code, includeReadme)
        break
      default:
        return { success: false, error: `Unsupported library: ${libraryId}` }
    }

    // Determine export filename
    const exportFilename = filename || `maigeXR_${libraryId}_scene`

    if (format === 'html') {
      // Single HTML file export
      const htmlContent = exportData.files[exportData.mainFile] || ''
      return await saveFile(htmlContent, `${exportFilename}.html`, 'text/html')
    } else if (format === 'json') {
      // JSON export (useful for debugging)
      const jsonContent = JSON.stringify(exportData.files, null, 2)
      return await saveFile(jsonContent, `${exportFilename}.json`, 'application/json')
    } else {
      // ZIP export
      return await createZipExport(exportData.files, `${exportFilename}.zip`)
    }
  } catch (error) {
    return {
      success: false,
      error: String(error)
    }
  }
}

/**
 * Generate Babylon.js export files
 */
function generateBabylonJSExport(code: string, includeReadme: boolean): { files: Record<string, string>; mainFile: string } {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Babylon.js Scene - maigeXR</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        html, body { width: 100%; height: 100%; overflow: hidden; }
        #renderCanvas {
            width: 100%;
            height: 100%;
            touch-action: none;
            display: block;
        }
    </style>
    <script src="https://cdn.babylonjs.com/babylon.js"></script>
    <script src="https://cdn.babylonjs.com/loaders/babylonjs.loaders.min.js"></script>
    <script src="https://cdn.babylonjs.com/gui/babylon.gui.min.js"></script>
</head>
<body>
    <canvas id="renderCanvas"></canvas>
    <script src="scene.js"></script>
</body>
</html>`

  const sceneJs = `// Babylon.js Scene - Generated by maigeXR
// https://maigexr.com

const canvas = document.getElementById('renderCanvas');
const engine = new BABYLON.Engine(canvas, true);

${code}

window.addEventListener('resize', () => engine.resize());
`

  const files: Record<string, string> = {
    'index.html': html,
    'scene.js': sceneJs
  }

  if (includeReadme) {
    files['README.txt'] = `maigeXR - Babylon.js Scene Export
================================

This scene was created with maigeXR (https://maigexr.com)

USAGE:
1. Open index.html in a modern web browser
2. No server required - works with file:// protocol

NOTES:
- Babylon.js v8.x is loaded from CDN
- Scene code is in scene.js
- Modify scene.js to customize

REQUIREMENTS:
- Modern web browser (Chrome, Firefox, Safari, Edge)
- WebGL support

Generated: ${new Date().toISOString()}
`
  }

  return { files, mainFile: 'index.html' }
}

/**
 * Generate Three.js export files
 */
function generateThreeJSExport(code: string, includeReadme: boolean): { files: Record<string, string>; mainFile: string } {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Three.js Scene - maigeXR</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        html, body { width: 100%; height: 100%; overflow: hidden; }
        canvas { display: block; }
    </style>
    <script type="importmap">
    {
        "imports": {
            "three": "https://cdn.jsdelivr.net/npm/three@0.171.0/build/three.module.js",
            "three/addons/": "https://cdn.jsdelivr.net/npm/three@0.171.0/examples/jsm/"
        }
    }
    </script>
</head>
<body>
    <script type="module" src="scene.js"></script>
</body>
</html>`

  const sceneJs = `// Three.js Scene - Generated by maigeXR
// https://maigexr.com

import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

${code}
`

  const files: Record<string, string> = {
    'index.html': html,
    'scene.js': sceneJs
  }

  if (includeReadme) {
    files['README.txt'] = `maigeXR - Three.js Scene Export
==============================

This scene was created with maigeXR (https://maigexr.com)

USAGE:
1. Start a local HTTP server in this directory
2. Open http://localhost:port in a modern browser

STARTING A SERVER:
- Python 3: python -m http.server 8000
- Node.js: npx serve .
- VS Code: Use Live Server extension

NOTES:
- Three.js r171 is loaded from CDN via ES6 modules
- Scene code is in scene.js
- Import map handles module resolution

REQUIREMENTS:
- Modern web browser with ES6 module support
- Local HTTP server (file:// wont work due to CORS)

Generated: ${new Date().toISOString()}
`
  }

  return { files, mainFile: 'index.html' }
}

/**
 * Generate A-Frame export files
 */
function generateAFrameExport(code: string, includeReadme: boolean): { files: Record<string, string>; mainFile: string } {
  // A-Frame code is typically HTML, so we embed it directly
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>A-Frame Scene - maigeXR</title>
    <script src="https://aframe.io/releases/1.7.0/aframe.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/c-frame/aframe-extras@7.5.0/dist/aframe-extras.min.js"></script>
    <style>
        * { margin: 0; padding: 0; }
    </style>
</head>
<body>
    ${code}
</body>
</html>`

  const files: Record<string, string> = {
    'index.html': html
  }

  if (includeReadme) {
    files['README.txt'] = `maigeXR - A-Frame Scene Export
==============================

This scene was created with maigeXR (https://maigexr.com)

USAGE:
1. Open index.html in a modern web browser
2. Click and drag to look around
3. Use WASD keys to move
4. Connect a VR headset for immersive mode

VR MODE:
- Click the VR goggles icon (bottom right)
- Requires WebXR-compatible browser and headset

NOTES:
- A-Frame v1.7.0 is loaded from CDN
- Scene markup is embedded in index.html
- Supports WebXR (VR/AR)

REQUIREMENTS:
- Modern web browser with WebGL
- VR headset optional (Oculus, Vive, etc.)

Generated: ${new Date().toISOString()}
`
  }

  return { files, mainFile: 'index.html' }
}

/**
 * Generate React Three Fiber export files
 */
function generateR3FExport(code: string, includeReadme: boolean): { files: Record<string, string>; mainFile: string } {
  const packageJson = JSON.stringify({
    name: 'maigexr-r3f-scene',
    version: '1.0.0',
    private: true,
    dependencies: {
      'react': '^18.2.0',
      'react-dom': '^18.2.0',
      '@react-three/fiber': '^8.15.0',
      '@react-three/drei': '^9.107.0',
      'three': '^0.171.0'
    },
    scripts: {
      'start': 'react-scripts start',
      'build': 'react-scripts build'
    },
    browserslist: {
      production: ['>0.2%', 'not dead', 'not op_mini all'],
      development: ['last 1 chrome version', 'last 1 firefox version', 'last 1 safari version']
    }
  }, null, 2)

  const indexHtml = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>React Three Fiber Scene - maigeXR</title>
</head>
<body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
</body>
</html>`

  const indexJs = `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './index.css';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`

  const indexCss = `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

html, body, #root {
  width: 100%;
  height: 100%;
  overflow: hidden;
}
`

  const appJs = `// React Three Fiber Scene - Generated by maigeXR
// https://maigexr.com

import React, { useRef, useState, useEffect } from 'react';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { OrbitControls, Environment, Html, Stats } from '@react-three/drei';
import * as THREE from 'three';

${code}
`

  const gitignore = `# Dependencies
/node_modules

# Production
/build

# Environment
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Logs
npm-debug.log*
yarn-debug.log*
yarn-error.log*
`

  const files: Record<string, string> = {
    'package.json': packageJson,
    'public/index.html': indexHtml,
    'src/index.js': indexJs,
    'src/index.css': indexCss,
    'src/App.js': appJs,
    '.gitignore': gitignore
  }

  if (includeReadme) {
    files['README.txt'] = `maigeXR - React Three Fiber Scene Export
========================================

This scene was created with maigeXR (https://maigexr.com)

SETUP:
1. Install Node.js (https://nodejs.org)
2. Open terminal in this directory
3. Run: npm install
4. Run: npm start
5. Open http://localhost:3000 in browser

BUILDING FOR PRODUCTION:
- Run: npm run build
- Deploy the /build folder to any static host

PROJECT STRUCTURE:
- src/App.js - Your R3F scene component
- src/index.js - React entry point
- public/index.html - HTML template
- package.json - Dependencies

DEPENDENCIES:
- React 18
- React Three Fiber 8.x
- React Three Drei 9.x
- Three.js r171

Generated: ${new Date().toISOString()}
`
  }

  return { files, mainFile: 'public/index.html' }
}

/**
 * Save a file using appropriate method for platform
 */
async function saveFile(
  content: string,
  filename: string,
  mimeType: string
): Promise<ExportResult> {
  if (isElectron()) {
    const api = getElectronAPI()
    if (api) {
      const result = await api.fileSystem.saveFile({
        defaultPath: filename,
        filters: [
          { name: 'All Files', extensions: ['*'] }
        ],
        data: content,
        encoding: 'utf8'
      })

      return {
        success: result.success,
        path: result.path,
        error: result.error
      }
    }
  }

  // Web fallback - use download
  try {
    const blob = new Blob([content], { type: mimeType })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)

    return { success: true, filename }
  } catch (error) {
    return { success: false, error: String(error) }
  }
}

/**
 * Create a ZIP file from multiple files
 */
async function createZipExport(
  files: Record<string, string>,
  filename: string
): Promise<ExportResult> {
  try {
    // Dynamically import JSZip
    const JSZip = (await import('jszip')).default
    const zip = new JSZip()

    // Add all files to the zip
    for (const [path, content] of Object.entries(files)) {
      zip.file(path, content)
    }

    // Generate the zip file
    const zipBlob = await zip.generateAsync({
      type: 'blob',
      compression: 'DEFLATE',
      compressionOptions: { level: 9 }
    })

    if (isElectron()) {
      const api = getElectronAPI()
      if (api) {
        // Convert blob to Uint8Array
        const arrayBuffer = await zipBlob.arrayBuffer()
        const uint8Array = new Uint8Array(arrayBuffer)

        const result = await api.fileSystem.saveFile({
          defaultPath: filename,
          filters: [
            { name: 'ZIP Archives', extensions: ['zip'] }
          ],
          data: uint8Array,
          encoding: 'binary'
        })

        return {
          success: result.success,
          path: result.path,
          error: result.error
        }
      }
    }

    // Web fallback - use download
    const url = URL.createObjectURL(zipBlob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)

    return { success: true, filename }
  } catch (error) {
    // JSZip not available - fall back to HTML export
    console.warn('JSZip not available, falling back to HTML export')

    // Find the main HTML file
    const htmlFile = files['index.html'] || files['public/index.html'] || Object.values(files)[0]
    return saveFile(htmlFile, filename.replace('.zip', '.html'), 'text/html')
  }
}
